default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  username: <%= ENV['TODO_LIST_DATABASE_USER'] %>
  password: <%= ENV['TODO_LIST_DATABASE_PASS'] %>